name: threads
description: A Flutter project of Threads Clone.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/ic_launcher.png"
  adaptive_icon_foreground: "assets/icon/ic_launcher_foreground.png"
  adaptive_icon_background: "assets/icon/ic_launcher_background.png"
  adaptive_icon_padding: true
  min_sdk_android: 21

# flutter pub run flutter_launcher_icons

flutter_native_splash:
  image: assets/splash_screen/bkd1.png
  color: "#151515"
  android_disable_fullscreen: true
  # branding: assets/icon/branding.png
  # branding_mode: bottom

  # dart run flutter_native_splash:create

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  get: ^4.6.5
  scroll_snap_list: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/app_icons/
    - assets/icon/
    - assets/splash_screen/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
